version: "2"
linters:
  default: none
  enable:
    - dupl
    - errcheck
    - goconst
    - gosec
    - govet
    - ineffassign
    - staticcheck
  settings:
    dupl:
      threshold: 100
    gosec:
      severity: low
    govet:
      enable-all: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
